### ISSUE TITLE
feature: publish on Operatorhub

### ISSUE THREAD

**Issue by ibotty** [krestomatio/keydb-operator#75]
**What is the motivation or use case for the feature?**

Easy installation.

**Describe the solution you'd like**
One-click installation from operatorhub (within OpenShift or OKD).

See https://sdk.operatorframework.io/docs/olm-integration/ for documentation.  I can help/clarify questions and test on different clusters.

**Comment by jobcespedes** [comment]
It is now published in https://operatorhub.io/operator/keydb-operator
